name: Continuous Integration

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ruby:
    name: "Test Backend (Jekyll ${{ matrix.jekyll_version }}, Ruby ${{ matrix.ruby_version }})"
    runs-on: "ubuntu-latest"
    env:
      JEKYLL_VERSION: ${{ matrix.jekyll_version }}
    strategy:
      fail-fast: false
      matrix:
        ruby_version: ["2.7"]
        jekyll_version:
          - "~> 3.9"
          - "~> 4.0"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: "Set up Ruby ${{ matrix.ruby_version }}"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - name: Unit Tests
        run: bundle exec rspec
